### ISSUE TITLE
Can't seem to override the template with feed_template

### ISSUE THREAD

**Issue by sonicfive** [bobdenotter/rss-extension#5]
Hi,

I am trying to override the rss feed template using the feed_template property in config/bobdenotter-rssextension.yaml 
Can I provide a template in my theme directory? It's not very clear how can this be achieved. 

Thanks!

**Comment by LimpSquid** [comment]
I'm hitting the same wall as you @sonicfive. As far as I can tell this is just a feature that is yet to be implemented, e.g. at https://github.com/bobdenotter/rss-extension/blob/master/src/Controller.php#L25 the paths for the different sitewide feeds seems to be just hardcoded.
 
I don't mind to put in some time to make a MR which implements this feature for at least the `sitewide` configuration. @bobdenotter Could you give a (N)ACK for this proposal, thanks!

**Comment by bobdenotter** [comment]
Fixed by recent PR. :-)
